sudo: required

services: 
    - docker

before_install:
    - docker build -t bigdev2000/docker-learning -f Dockerfile.dev .

script:
    - docker run bigdev2000/docker-learning npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: docker-learning
    env: [env_name]
    bucket_name: "[name]"
    bucket_path: "docker-learning"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"