sudo: required

services: 
    - docker

before_install:
    - docker build -t bigdev2000/docker-learning -f Dockerfile.dev .

script:
    - docker run bigdev2000/docker-learning npm run test -- --coverage