version: '3'
services: 
    front_end:
        build:
            context: .
            # tell where all file and folder we pull from
            dockerfile: Dockerfile.dev
            # location of dockerfile that we will use to construct the image
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            # don't try to map with this folder
            - .:/app
            # map outside to inside
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
