FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .
# leave it like this, if you use docker-compose and map the folder
# when making real product you wont use mapping folder so no need to remove this line

CMD ["npm", "run", "start"]

# we we just install create-react tool, to generate new project
# node_modules has a ton of dependencies inside of it
# this file has a very large size
# but we want to have only dependencies in our image not in this
# so delete the node_modules folder 
# and run it again you will see it's faster than the old