# spcific base image
# # # FROM alpine >> {the first error}
# alpine is very small, not much program are installed
# 2 option = {find dif base image(contain node and npm), attemp to install node and npm}
# find it on docker hub >> https://hub.docker.com/search?q=node&type=image
# FROM [image]:[tag]
FROM node:alpine

# install some dependencies
# # # RUN npm install
# error "no such file or directory, open '/package.json"
# because in the it is the diff part of hardware secment
# use COPY [local(relatively)] [inside container]
COPY ./ ./
RUN npm install

# Default command
CMD ["npm", "start"]